In [54]:
# Load dataset
df = pd.read_csv('Customer_Churn.csv')

# Preview data
print("Dataset preview:")
print(df.head())

# Check column names
print("Column names in the dataset:")
print(df.columns)

# Identify target and features
target = 'Churn'

# Check if target column exists
if target not in df.columns:
    raise ValueError(f"Target column '{target}' not found in the dataset.")

# Handle missing values
# Fill numeric columns with median and categorical columns with mode
numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.drop(target, errors='ignore')

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Encode target
df[target] = df[target].map({'No': 0, 'Yes': 1})

# Encode categorical features
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Split features and target
X = df.drop(columns=[target])
y = df[target]

# Continue with the rest of the code...

Dataset preview:
              Names  Age  Total_Purchase  Account_Manager  Years  Num_Sites  \
0  Cameron Williams   42        11066.80                0   7.22          8
1     Kevin Mueller   41        11916.22                0   6.50         11
2       Eric Lozano   38        12884.75                0   6.67         12
3     Phillip White   42         8010.76                0   6.71         10
4    Cynthia Norton   37         9191.58                0   5.56          9

       Onboard_date                                           Location  \
0  30-08-2013 07:00     10265 Elizabeth Mission\nBarkerburgh, AK 89518
1  13-08-2013 00:38  6157 Frank Gardens Suite 019\nCarloshaven, RI ...
2  29-06-2016 06:20            1331 Keith Court\nAlyssahaven, DE 90114
3  22-04-2014 12:43      13120 Daniel Mount\nAngelabury, WY 30645-4695
4  19-01-2016 15:31               765 Tricia Row\nKarenshire, MH 71730

                       Company  Churn
0                   Harvey LLC      1
1                   Wilson PLC      1
2  Miller, Johnson and Wallace      1
3                    Smith Inc      1
4                   Love-Jones      1
Column names in the dataset:
Index(['Names', 'Age', 'Total_Purchase', 'Account_Manager', 'Years',
       'Num_Sites', 'Onboard_date', 'Location', 'Company', 'Churn'],
      dtype='object')